import './globals.css';

import { Roboto } from 'next/font/google';

const roboto = Roboto({
    weight: ['400', '700'],
    style: ['normal', 'italic'],
    subsets: ['latin'],
    display: 'swap',
});

import Nav from '@/components/Nav';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={`bg-blue-100 ${roboto.className}`}>
                <div id="__next" className="p-3">
                    <Nav />
                    {children}
                </div>
            </body>
        </html>
    );
}
